name: ci-client

on:
  push:
    branches:
      - main
    paths:
      - "packages/client/**"
      # Generic files
      - ".github/workflows/ci-client.yml"
      - "yarn.lock"
  pull_request:
    paths:
      - "packages/client/**"
      # Generic files
      - ".github/workflows/ci-client.yml"
      - "yarn.lock"

jobs:
  test:
    runs-on: ubuntu-latest
    timeout-minutes: 7

    steps:
      - uses: actions/checkout@v2
      - uses: volta-cli/action@v1
      - uses: mydea/actions-ember-testing@v2
      - name: Install dependencies
        run: yarn install --frozen-lockfile
      - name: Run tests
        run: yarn test:ember
        working-directory: packages/client
      - name: Lint
        run: yarn lint
        working-directory: packages/client

  test-matrix:
    runs-on: ubuntu-latest
    timeout-minutes: 7

    strategy:
      matrix:
        # Keep this in sync with config/ember-try.js
        ember:
          [
            ember-lts-3.24,
            ember-lts-3.28,
            ember-release,
            ember-beta,
            ember-canary,
            embroider-safe,
            embroider-optimized,
          ]

    steps:
      - uses: actions/checkout@v2
      - uses: volta-cli/action@v1
      - uses: mydea/actions-ember-testing@v2
      - name: Install dependencies
        run: yarn install --frozen-lockfile
      - name: Run tests
        run: yarn test:ember-one ${{ matrix.ember }}
        working-directory: packages/client
